export let addressUrl =
  "https://api.addressy.com/Capture/Interactive/Find/v1.10/json3.ws?";

export let paths = {
  calculator: "/calculator",
  zakat: "/zakat",
  donation: "/donation",
  support: "/support",
  payment: "/payment",
  thankYou: "/thank-you",
  otherWays: "/other-ways",
  directDebitGuarantee: "/direct-debit-guarantee",
  stPaymentError: "/st-payment",
};

export let paymentTypes = {
  single: "One-off payment",
  regular: "Regular Payment",
};

export let donationNames = {
  rib: "Riba",
  sad: "Sadaqah",
  zakat: "Zakat",
};

export let sadaqahDisplayName = donationNames.sad + " (voluntary donation)";
export let ribbahDisplayName = donationNames.rib + " (interest)";

export let giftAidPercent = 25;

export let deliveryPercent = 10;

export let deliveryFeeText = "Distribution service";
export let deliveryFeeTextNoAddOn = "Support cost";

export let emptySplit = [
  {
    name: "Hardship Relief",
    recommended: 0.7,
    split: 0,
    amount: 0,
    id: 0,
  },
  {
    name: "Housing & Work",
    recommended: 0.2,
    split: 0,
    amount: 0,
    id: 1,
  },
  {
    name: "Education",
    recommended: 0.1,
    split: 0,
    amount: 0,
    id: 3,
  },
];

export function EmptyObjectFunc() {
  this.content = {
    mode: "",
    loadingText: false,
    count: 0,
    user: {
      assets: {
        gold: "",
        silver: "",
        cash: {
          inHand: "",
          inBank: "",
          sharesCapital: "",
          sharesDividend: "",
          receivables: "",
          cashIsa: "",
          sharesInvestments: "",
          pension: "",
          crypto: "",
          cashOwedToYou: "",
          loanOwedToYou: "",
          soldOwedToYou: "",
          other: [],
        },
        goldSilver: {
          other: [],
        },
        moneyOwed: {
          other: [],
        },
        crypto: {
          other: [],
        },
        investment: {
          other: [],
        },
        businessAssets: {
          cash: "",
          receivables: "",
          stock: "",
          other: [],
        },
        liabilities: {
          housePayments: "",
          bills: "",
          borrowed: "",
          overdraft: "",
          credit: "",
          tax: "",
          other: [],
        },
      },
      reccommendZakat: 0,
      paymentDetails: {
        paymentType: 2,
        cardType: "",
        cardNumber: 0,
        securityCode: 0,
        issueDate: "",
        expiryDate: "",
        issueNum: 0,
        cardName: "",
        accountHolderName: "",
        accountNumber: "",
        bankSortCode: "",
        numberOfPayments: 12,
        paymentStartDate: "",
        title: "",
        firstName: "",
        lastName: "",
        companyName: "",
        postCode: "",
        address: {
          lineOne: "",
          lineTwo: "",
          lineThree: "",
          townCity: "",
          countyRegion: "United Kingdom",
          postCode: "",
          emailAddress: "",
          contactNumber: "",
          altNumber: "",
        },
        optIn: {
          email: false,
          sms: false,
          post: false,
          phone: false,
          whatsapp: false,
          telegram: false,
        },
        contactSubject: [],
      },
      cardDetails: {
        accounttypedescription: "",
        acquirerresponsecode: 0,
        authcode: "",
        baseamount: 0,
        cavv: "",
        currencyiso3a: "",
        customeroutput: "",
        dccenabled: 0,
        eci: 5,
        enrolled: "",
        errorcode: 0,
        errormessage: "",
        issuer: "",
        issuercountryiso2a: "",
        livestatus: 0,
        maskedpan: "",
        merchantcountryiso2a: "",
        merchantname: "",
        merchantnumber: "",
        operatorname: "",
        parenttransactionreference: "",
        paymenttypedescription: "",
        requesttypedescription: "",
        securityresponseaddress: 0,
        securityresponsepostcode: 0,
        securityresponsesecuritycode: 2,
        settleduedate: "2019-11-15",
        settlestatus: 0,
        splitfinalnumber: 1,
        status: "",
        threedversion: "",
        tid: 0,
        transactionreference: 0,
        transactionstartedtimestamp: "2019-11-15 08:15:02",
        xi: "",
      },
    },
    donation: {
      allocation: "nzf",
      zakat: "",
      donationTypes: [
        {
          name: "Zakat",
          amount: 0,
          id: 0,
          paymentType: paymentTypes.single,
        },
      ],
      administration: {
        optIn: false,
        amount: 0,
      },
      totalDonation: 0,
      totalChargeable: 0,
      donationSplit: [
        {
          name: "Hardship Relief",
          recommended: 0.7,
          split: 0,
          amount: 0,
          id: 0,
        },
        {
          name: "Housing & Work",
          recommended: 0.2,
          split: 0,
          amount: 0,
          id: 1,
        },
        {
          name: "Education",
          recommended: 0.1,
          split: 0,
          amount: 0,
          id: 3,
        },
      ],
      giftAid: false,
      giftAidClicked: false,
      giftAidAmount: 0,
    },
    secureTrading: {
      jwt: null,
      generatedAt: null,
      paymentData: {},
    },
    inputs: {
      selectOpen: 0,
    },
    messages: {
      messageOpen: 0,
    },
    zakatCalculation: {
      selectedPension: "Bonds/Fixed interest/Gilts",
      pensions: {
        "Bonds/Fixed interest/Gilts": 1,
        "Shariah compliant scheme": 0.26,
        "Mixed portfolio": 0.5,
        Equity: 0.27,
        "Direct/physical property": 0.15,
      },
      investments: {
        stocks: 0.25,
      },
    },
    transitions: {
      to: "",
      from: "",
      history: [],
      isNavOpen: false,
      scrollTo: "",
    },
    calculationSettings: {
      showPension: false,
      pensionKnown: 0,
      deliveryCost: 2,
    },
    nissab: {
      // gold_price: 36.742,
      // silver_price: 0.4286,
      // nisab_gold_value: 3214.1902,
      // nisab_silver_value: 262.4575
    },
    errors: {
      show: false,
      globalErrors: [],
    },
    paymentSubmit: {
      loading: false,
      errors: false,
      msg: "",
    },
    calculatorProgress: 0,
    goldSilverWeightSettings: {
      silver: false,
      silverWeight: "",
      gold: false,
      goldWeight: "",
    },
  };
}

export const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo (the Democratic Republic of the)",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "South Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States Minor Outlying Islands",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];
