export let labels = {
    'cashInHand': 'Cash in Hand',
    'cashInBank': 'Cash in Bank',
    'cashInBankAccounts': 'Cash in Bank Accounts',
    'cashOwedToYou': 'Cash owed to you',
    'shareAndInvestments': 'Share and investments',
    'loan': 'Loan',
    'somethingIHaveSold': 'Something I have sold',
    'moneyOwedToYou': 'Money Owed To You',
    'needHelp': 'Need help?',
    'goldSilverValuation': 'Gold & Silver',
    'goldValuation': 'Gold valuation',
    'silverValuation': 'Silver valuation',
    'cashValuation': 'Cash valuation',
    'sharesPrivateEquityInvestments': 'Shares & Private Equity Investments',
    'sharesBoughtToResellForCapitalGain': 'Shares bought to resell for capital gain',
    'sharesBoughtAsALongTermInvestmentForDividendIncome': 'Shares bought as a long term investment for dividend income',
    'iKnowTheZakatableAmountOfMyPension': 'I know the Zakatable amount of my pension',
    'iDontKnowTheZakatableAmountOfMyPension': 'I don’t know the Zakatable amount of my pension',
    'pensions': 'Pensions',
    'fullAmount': 'Full amount',
    'isasJuniorIsasChildTrustFunds': 'ISA’s, Junior ISA’s & Child Trust Funds',
    'stocksSharesIsactf': 'Stocks & shares ISA/CTF',
    'cashIsa': 'Cash ISA',
    'cryptoAssets': 'Crypto assets',
    'currentCashValuation': 'Current cash valuation',
    'businessAssets': 'Business Assets',
    'cash': 'Cash',
    'receivables': 'Receivables',
    'stock': 'Stock',
    'liabilitiesMoneyYouOwe': 'Liabilities/Money You Owe',
    'theFollowingAmountsAreDueToBePaidTodayOrAreOverdue': 'The following amounts are due to be paid today or are overdue:',
    'mortgage': 'Mortgage',
    'utilityBills': 'Utility bills',
    'personalLoans': 'Personal loans',
    'overdraft': 'Overdraft',
    'creditCard': 'Credit card',
    'tax': 'Tax',
    'thankYouForYourDonation': 'Thank you for your donation!',
    'seeHowYourMoneyCanDirectlyHelpMuslimsInTheUk': 'See how your money can directly help Muslims in the UK.',
    'shareToEncourageOthersToDonateTheirZakat': 'Share to encourage others to donate their zakat:',
    'myPayableZakat': 'My Payable Zakat:',
    'yourZakatCalculation':'Your zakat calculation',
    'yourZakatableAssets':'Your zakatable assets',
    'yourLiabilities':'Your liabilities',
    'netAssets':'Net assets',
    'nisabValue':'Nisab Value',
    'yourDonationsAndPaymentTypes':'Your donations and payment types.',
    'selectYourTypeOfDonationAndHowYouWouldLikeToPayBelow':'Select your type of donation and how you would like to pay below:',
    'iWantToGiveSadaqahOrRiba':'I want to give Sadaqah or Riba',
    'scrollUpForPreviousQuestion':'Scroll up for previous question',
    'howYouCanHelp': 'How you can help.',
    'youCanChooseWhereYourZakatIsDistributed':'You can choose where your Zakat is distributed',
    'howYouCanHelpNzfGoEvenFurther': 'How you can help NZF go even further',
    'iWantToGiveZakat': 'I want to give zakat',
    'addAFree25ToMyDonationThroughGiftAid':'Add a free 25% to my donation through Gift Aid',
    'pleaseFillInYourDetailsBelowToCompleteYourDonation':'Please fill in your details below to complete your donation…',
    'title':'Title*',
    'singleDonationPaymentDetails':'Single donation payment details',
    'regularDonationPaymentDetails':'Regular donation payment details',
    'selectPaymentType':'Select Payment Type',
    'wedLikeToContactYouAboutTheWorkWeDo':'We’d like to contact you about the work we do',
    'whatSubjectWouldYouLikeToStayInformedAbout':'What subject would you like to stay informed about?',
    'howWouldYouLikeUsToContactYou':'How would you like us to contact you?',
    'selectYourPreferredMethodOfContactForTheFuture':'Select your preferred method of contact for the future…',
    'completePayment':'Complete Payment',
    'myDonationBasket':'My donation basket',
    'singlePayments':'Single Payments',
    'subtotal':'Subtotal:',
    'regularPayments':'Regular Payments',
    'yourDetails':'Your details',
    'total':'Total:',
    'anExtra25WillBeAddedToYourDonationTotalThroughGiftAidAtNoExpenseToYou':'An extra 25% will be added to your donation total through Gift Aid at no expense to you.',
    'donateUsing':'Donate using',
    'orExploreOtherWaysToPay':'Or explore other ways to pay',
    'Would you like to round up your zakat':'Would you like to round up your zakat?',
    'yourPayableZakat':'Your payable zakat:',
    'whereItsMostNeeded': "Where it's most needed",
    'allocateEvenly':'Allocate evenly',
    'wellHelpYouCalculateYourZakatToDonateToWorthyPeopleInNeed':'We’ll help you calculate your Zakat to donate to worthy people in need.',
    'enterInTheAmountOfCashYouOwnThisIncludesStocksAndSharesAndEvenSavingsUnderYourMattress':'Enter in the amount of cash you own. This includes stocks and shares and even savings under your mattress.',
    'typeOfPensionScheme':'Type of pension scheme',
    'youHaveAllocated100OfYourDonationTotal':'You have allocated 100% of your donation total.',
    'addAnotherField':'Add another field',
    'pleaseEnterAValidPostCode':'Please enter a valid post code.',
    'enterAddressManually':'Enter address manually',
    'zakatLeftToAllocate' : 'zakat left to allocate',
    'donationAmount':'Donation Amount',
    'paymentType':'Payment Type',
    'calculator':'Calculator',
    'giveZakat':'Give zakat',
    'supportNzf':'Support NZF',
    'payment':'Payment',
    'otherWaysToPay':'Other ways to pay',
    'goldWeight':'Gold Weight',
    'silverWeight':'Silver Weight',
    'wellHelpYouParagraph': 'well Help You Paragraph.',
    'cashToolTip':'cash tool tip!',
    'moneyOwedParagraph':'Money Owed Paragraph.',
    'moneyOwedToolTip':'money owed tool tip!',
    'goldParagraph': 'Gold Paragraph.',
    'goldToolTip':'Gold Tool Tip.',
    'sharesParagraph': 'Shares Paragraph.',
    'sharesToolTip':'Shares Tool Tip.',
    'pensionParagraph':'Pension Paragraph.',
    'pensionToolTip':'Pension tool tip.',
    'isaParagraph':'ISA Paragraph.',
    'isaToolTip':'isa tool tip.',
    'cryptoParagraph':'Crypto Paragraph.',
    'cryptoToolTip':'Crypto Tool Tip.',
    'businessParagraph':'Business Paragraph.',
    'businessToolTip':'Business Tool Tip.',
    'liabilitiesParagraph':'Liabilities Paragraph.',
    'liabilitiesToolTip':'Liabilities Tool Tip.',
    'supportParagraph':'Support Paragraph.',
    'giftAidParagraph':'Gift Aid Paragraph.',
    'zakatDisplayParagraph':'Zakat Display Paragraph.',
    'roundupParagraph':'Roundup Paragraph.',
    'muslimsInPovertyToolTip':'Muslims in Poverty Tool Tip.',
    'leadershipSchemesToolTip':'Leadership Schemes Tool Tip.',
    'Homeless Muslims Tool Tip':'Homeless Muslims Tool Tip.',


    'thankYouParagraph':'Thanks to your support, Muslims who need Zakat in the UK can get basic essentials like food, clothing and shelter and for other needs like training, legal help and education. This lets people get on the path to being financially independent and feel confident about their future. It’s amazing to see how this can have a direct and beneficial impact on their faith.',
    'nisabToolTip':'Nissab Tool Tip.',
    'shareParagraph' : 'Want your family and friends to make the impact you\'re making?',


    'nzfDeliveryParagraph':'We use up to 10% of your Zakat to cover the costs of distributing it. If you prefer 100% of your Zakat to go directly to those in need, you can give a voluntary (Sadaqah) add-on to cover the costs instead.'
};
